Nob/refactor form
per-sephone/SnakeSynth pull request #7
Opened 2023-10-27 23:04 UTC by per-sephone

- Added more detailed doc strings and type hints, removed unhelpful comments in form.py
- Refactored form.py by adding new functions and separating code into more specific functions

2023-10-31 02:44 UTC, jasonandmonte requested changes
I noticed that the `help` function and `.__doc__` attribute are not populating with the comments like I would expect. I think that the comments need to be put under the class/function header in order to have them associate correctly.

From:
```py
    """
    This function connects the knob values with the
    spinbox values for each knob/spinbox on the GUI
    """

    def connect_knob_and_spinbox_values(self, win):
```
To:
```py
    def connect_knob_and_spinbox_values(self, win):
        """
        This function connects the knob values with the
        spinbox values for each knob/spinbox on the GUI
        """
```

There is some examples on the PEP as well: https://peps.python.org/pep-0257/

Otherwise everything looks great!

2023-11-01 01:45 UTC, per-sephone commented
Implemented your suggestions, waiting on second code review before merging

2023-11-01 16:12 UTC, kaleb2 approved these changes

2023-11-01 16:37 UTC, jasonandmonte approved these changes
Looks good! 👍👍

2023-11-01 17:02 UTC, merged